flask_app/ISAQ/models.py
from flask_login import UserMixin
from ISAQ import db, login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    posts = db.relationship('Post', backref='author', lazy='dynamic')

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    description = db.Column(db.Text, nullable=False)
    registration_link = db.Column(db.String(100), default=None)
    picture_file = db.Column(db.String(20), nullable=False, default='default.png')
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

flask_app/ISAQ/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from ISAQ.config import Config

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'admin_b.login'

def create_app(config=Config):
    app = Flask(__name__)
    app.config.from_object(Config)
    
    bcrypt.init_app(app)
    login_manager.init_app(app)
    db.init_app(app)

    from ISAQ.admin.routes import admin_b
    from ISAQ.main.routes import main_b

    app.register_blueprint(admin_b)
    app.register_blueprint(main_b)

    return app

flask_app/ISAQ/admin/routes.py
import logging
import os
import secrets
from datetime import datetime

from flask import (Blueprint, current_app, flash, redirect, render_template,
                   request, url_for)
from flask_login import current_user, login_required, login_user, logout_user
from PIL import Image

from ISAQ import bcrypt, db
from ISAQ.models import Post, User

admin_b = Blueprint('admin_b', __name__)

@admin_b.route('/admin', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('admin_b.home'))
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        if username and password:
            user = User.query.filter_by(username=username).first()
            if user and bcrypt.check_password_hash(user.password, password):
                login_user(user)
                return redirect(url_for('admin_b.home'))
            else:
                flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('admin/login.html')

@admin_b.route("/admin/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('admin_b.login'))

@admin_b.route('/admin/home')
@login_required
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date.desc()).paginate(page=page, per_page=5)
    return render_template('admin/home.html', posts=posts)

@admin_b.route("/admin/post/<int:post_id>")
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("admin/post.html", post=post)

@admin_b.route('/admin/post/add', methods=['GET', 'POST'])
@login_required
def post_add():
    if request.method == 'POST':
        
        try:
            title = request.form.get('title')
            date = request.form.get('date')
            description = request.form.get('description')
            include_link = request.form.get('registration_link')
            new_post = Post(
                title=title, date=datetime.strptime(date, '%Y-%m-%d'),
                description=description, author=current_user
            )

            if include_link:
                registration_link = request.form.get('registration_link')
                new_post.registration_link = registration_link

            if request.files['picture'].filename:
                post_pic = request.files['picture']
                # Create random name for picture
                random_hex = secrets.token_hex(8)
                # Extract filename and file extension
                _, f_ext = os.path.splitext(post_pic.filename)
                pic_new_filename = random_hex + f_ext
                storing_path = os.path.join(current_app.root_path, 'static/img', pic_new_filename)

                # Create tuple of new size(width, length)
                output_size = (500, 500)
                
                # Resize picture and store
                # in static/badges 
                i = Image.open(post_pic)
                i.thumbnail(output_size)
                i.save(storing_path)
                new_post.picture_file = pic_new_filename
            
            # Add new post to database
            db.session.add(new_post)
            db.session.commit()
            flash('New post has been created!', 'success')
            
        except Exception as ex:
            logging.error('Unable to create new post beacuse %s', ex)
            flash('Unable to add a new post for a moment!', 'error')
        

    return render_template('admin/post_add.html')

@admin_b.route('/admin/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def post_update(post_id):
    post = Post.query.filter_by(id=post_id).first()
    if request.method == 'POST':

        title = request.form.get('title')
        date = request.form.get('date')
        description = request.form.get('description')
        include_link = request.form.get('include_link')
        
        post.title = title
        post.date = datetime.strptime(date, '%Y-%m-%d')
        post.description = description

        if include_link:
            registration_link = request.form.get('registration_link')
            post.registration_link = registration_link
        else:
            post.registration_link = None

        if request.files['picture'].filename:
            post_pic = request.files['picture']
            # Create random name for picture
            random_hex = secrets.token_hex(8)
            # Extract filename and file extension
            _, f_ext = os.path.splitext(post_pic.filename)
            pic_new_filename = random_hex + f_ext
            storing_path = os.path.join(current_app.root_path, 'static/img', pic_new_filename)

            # Create tuple of new size(width, length)
            output_size = (500, 500)
            
            # Resize picture and store
            # in static/badges 
            i = Image.open(post_pic)
            i.thumbnail(output_size)
            i.save(storing_path)
            post.picture_file = pic_new_filename
        
        # Save update data in database
        db.session.commit()

        return redirect(url_for('admin_b.post', post_id=post.id))
    return render_template('admin/post_update.html', post=post)

@admin_b.route("/admin/post/<int:post_id>/delete")
@login_required
def post_delete(post_id):
    post = Post.query.get_or_404(post_id)
    try:
        delete_path = os.path.join(current_app.root_path, 'static/img', post.picture_file)
        os.remove(delete_path)
        db.session.delete(post)
        db.session.commit()
        flash('Your post has been deleted!', 'success')
    except Exception as ex:
        print(ex)
    return redirect(url_for('admin_b.home'))

flask_app/ISAQ/main/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for, current_app
from ISAQ.models import Post

main_b = Blueprint('main_b', __name__)

@main_b.route('/')
def home():
    posts = Post.query.order_by(Post.date.desc()).limit(3).all()
    return render_template('main/home.html', posts=posts, home=True)

@main_b.route('/posts')
def posts():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date.desc()).paginate(page=page, per_page=5)
    return render_template('main/posts.html', posts=posts)

@main_b.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("main/post.html", post=post)

flask_app/ISAQ/templates/main/home.html
{% extends 'main/layout.html' %}
{% block content %}
  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
      <div class="row justify-content-center">
        <div class="col-xl-7 col-lg-9 text-center">
          <h1>Indonesian Student Association of QUT</h1>
        </div>
      </div>
  
      </div>

    </div>
  </section>

  <main id="main">
    <!-- ======= Post Section ======= -->
    <section id="latest-post" class="about">

      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Latest Post</h2>
        </div>
        
        <div class="row mt">
          {% for post in posts %}
            
              <div class="col-lg-4 col-md-4 col-xs-12 desc" style="padding-left: 50px; padding-right: 50px;">

                <a class="b-link-fade b-animate-go" ><img width="100%" src="{{ url_for('static', filename='img/' + post.picture_file) }}" />
                </a>
                <p style="min-height: 40px; overflow: hidden; text-align: center; font-size: 18px;"> <b><a href="{{ url_for('main_b.post', post_id=post.id) }}"> {{ post.title }} </a></b> </p>
                <p style="max-height: 150px; overflow: hidden;">{{ post.description }}</p>
                <hr-d>
                  <p class="time"><i class="bx bx-calendar"></i> {{ post.date.strftime('%d %B %Y') }} </p>
              </div>
            
          {% endfor %}
        </div>

        <a href="{{ url_for('main_b.posts') }}" class="btn-general">All Posts</a>
      </div>
      
    </section><!-- End Post Section -->


    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>About Us</h2>
        </div>

        <div class="row content">
          <div class="col-lg-6">
            <img width="90%" src="{{url_for('static', filename='img/bg01.JPG') }}" alt="" />
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0">
            <p>
              Indonesian Student Association of QUT (ISAQ) is a branch of Indonesian organisation named Perhimpunan Pelajar Indonesia Australia (PPIA) that facilitates the entire community of Indonesian students who conducted study at the Queensland University of Technology (QUT) to assist and build a network with one another. ISAQ is also widely open to all other QUT students who are interested in Indonesia. Through ISAQ, all members can receive the latest updates about the study news, events and exciting activities.
            </p>
          </div>
        </div>

      </div>
    </section><!-- End About Section -->

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Contact Us</h2>
        </div>

        <div>
          <iframe style="border:0; width: 100%; height: 270px;" src="https://maps.google.com/maps?q=qut&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" allowfullscreen></iframe>
        </div>

        <div class="row mt-5">

          <div class="col-lg-4">
            <div class="info">
              <div class="address">
                <i class="icofont-google-map"></i>
                <h4>Location:</h4>
                <p>2 George St, Brisbane City QLD 4000</p>
              </div>

              <div class="email">
                <i class="icofont-envelope"></i>
                <h4>Email:</h4>
                <p>isaq@isa-qut.org</p>
              </div>

            </div>

          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->

  </main><!-- End #main -->
{% endblock %}

flask_app/ISAQ/templates/main/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>ISAQ</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{ url_for('static', filename='img/Logo-noname.png') }}" rel="icon">
  <link href="{{ url_for('static', filename='img/Logo-noname.png') }}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/icofont/icofont.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/remixicon/remixicon.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/venobox/venobox.css') }}" rel="stylesheet">
  
  <link href="{{ url_for('static', filename='vendor/aos/aos.css') }}" rel="stylesheet"> 

  <!-- Template Main CSS File -->
  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

  {% block style %}
  {% endblock %}
</head>

<body>
    
    
    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">

            <a href="{{ url_for('main_b.home') }}" class="logo mr-auto"><img src="{{ url_for('static', filename='img/Logo.png') }}" class="img-fluid"></a>
            <nav class="nav-menu d-none d-lg-block">
                    <ul>
                        <li><a href="{{ url_for('main_b.home') }}">Home</a></li>
                        {% if home %}
                            <li><a href="#latest-post">Posts</a></li>
                            <li><a href="#about">About Us</a></li>
                            <li><a href="#contact">Contact Us</a></li>
                        {% else %}
                            <li><a href="{{ url_for('main_b.posts') }}">Posts</a></li>
                            <li><a href="{{ url_for('main_b.home') }}#about">About Us</a></li>
                            <li><a href="{{ url_for('main_b.home') }}#contact">Contact Us</a></li>
                        {% endif %}
                    </ul>
            </nav><!-- .nav-menu -->
        </div>
    </header><!-- End Header -->

    {% block content %}
    {% endblock %}

    <!-- ======= Footer ======= -->
    <footer id="footer">

        <div class="container d-md-flex py-4">

        <div class="mr-md-auto text-center text-md-left">
            
        </div>
        <div class="social-links text-center text-md-right pt-3 pt-md-0">
            <a href="https://twitter.com/ppia_qut" class="twitter"><i class="bx bxl-twitter"></i></a>
            <a href="https://fb.com/ppiaisaq" class="facebook"><i class="bx bxl-facebook"></i></a>
            <a href="https://instagram.com/ppiaqut" class="instagram"><i class="bx bxl-instagram"></i></a>
        </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>
    <div id="preloader"></div>


  <!-- Vendor JS Files -->
  <script src=" {{url_for('static', filename='vendor/jquery/jquery.min.js')}} "></script>
  <script src="{{url_for('static', filename=' vendor/bootstrap/js/bootstrap.bundle.min.j')}}s "></script>
  <script src=" {{url_for('static', filename='vendor/jquery.easing/jquery.easing.min.js')}} "></script>
  <script src=" {{url_for('static', filename='vendor/php-email-form/validate.js')}} "></script>
  <script src=" {{url_for('static', filename='vendor/waypoints/jquery.waypoints.min.js')}} "></script>
  <script src=" {{url_for('static', filename='vendor/counterup/counterup.min.js')}} "></script>
  <script src=" {{url_for('static', filename='vendor/venobox/venobox.min.js')}} "></script>
  <script src=" {{url_for('static', filename='vendor/owl.carousel/owl.carousel.min.js')}} "></script>
  <script src=" {{url_for('static', filename='vendor/isotope-layout/isotope.pkgd.min.js')}} "></script>
  <script src=" {{url_for('static', filename='vendor/aos/aos.js')}} "></script>

  <!-- Template Main JS File -->
  <script src=" {{url_for('static', filename='js/main.js')}} "></script>

</body>

</html>

flask_app/ISAQ/templates/main/post.html
{% extends 'main/layout.html' %}
{% block style %}
<style>
  .container p{
    color: black;
  }
  #content-text{
      font-size: 15px;
      text-align: left;
  }
</style>
{% endblock %}
{% block content %}

  <div class="container">
    <div class="section-title" style="margin-top: 150px;">
      <img src="{{ url_for('static', filename='img/'+post.picture_file) }}" style="max-height: 300px;">
      <h2 style="margin-top: 30px;">{{ post.title }}</h2>
      <hr-d>
          <p class="time" style="color: black; font-size: 18px; font-weight: 700;"><i class="bx bx-calendar"></i>{{ post.date.strftime('%d %B %Y') }}</p>
      <p id="content-text" style="margin-top: 30px;">{{ post.description }}</p>

      {% if post.registration_link %}
        <a href="{{ post.registration_link }}" class="btn-general">REGISTER</a>
      {% endif %}
    </div>
  </div>
{% endblock %}

flask_app/ISAQ/templates/main/posts.html
{% extends 'main/layout.html' %}
{% block content %}
  <div class="section-title" style="margin-top: 150px;">
    <h2>All Post</h2>
  </div>

  {% if posts %}
    <div id="post-list">
      {% for post in posts.items %}
        <div class="row mt post-box" style="margin-top: 60px;">

          <div class="col-lg-3 col-md-3 col-xs-12 desc" style="padding-left: 20px; padding-right: 20px; text-align: center;">

            <a class="b-link-fade b-animate-go"><img src="{{ url_for('static', filename='img/' + post.picture_file) }}"/>
            </a>
                
          </div>

          <div class="col-lg-8 col-md-8 col-xs-12 desc">
            <h3> <a href="{{ url_for('main_b.post', post_id=post.id) }}"> {{ post.title }} </a> </h3>
            <p> {{ post.description }} </p>
            <hr-d>
            <p class="time"><i class="bx bx-calendar"></i> {{ post.date.strftime('%d %B %Y') }} </p>
          </div>

        </div>
      {% endfor %}
      <div class="section-title" style="margin-top: 150px;">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('main_b.posts', page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main_b.posts', page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
          ...
        {% endif %}
        {% endfor %}
      </div>
    </div>
  {% else %}
    <div class="section-title" style="margin-top: 150px;">
      <h3>No posts yet</h3>
    </div>
  {% endif %}
{% endblock %}